INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'Notebook');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'Smartphone');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1003, 'Tablet');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Mercado Livre');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1002, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1001, 'Lenovo L340 Gamer', 1001, 1001, 25, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1002, 'Samsung Galaxy Book 360 Pro', 1002, 1001, 10, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1003, 'Dell XPS 13', 1001, 1001, 12, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1004, 'Samsung Galaxy S21', 1002, 1002, 55, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1005, 'Iphone 13 Pro Max', 1002, 1002, 37, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1006, 'Samsung Galaxy Tab S7', 1001, 1003, 7, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1007, 'Ipad Pro', 1002, 1003, 9, CURRENT_TIMESTAMP);
